#!/bin/bash
# Submit improved Stage0/Stage1/Stage2 training at 150 epochs.
#
# Stage0: uniform baseline sweep (darknet/resnet x q4/q6/q8)
# Stage1: adaptive ROI sweep (darknet/resnet x lr)
# Stage2: adaptive+distill sweep (lambda_distill array), submitted for configured backbone(s)
#
# Usage:
#   bash src/scripts/submit_stage012_improved_150.sh

set -euo pipefail

if ! command -v sbatch >/dev/null 2>&1; then
  echo "Error: sbatch not found. Run this on a Slurm login node." >&2
  exit 1
fi

mkdir -p logs

EPOCHS=${EPOCHS:-150}
BATCH_SIZE=${BATCH_SIZE:-4}
NUM_WORKERS=${NUM_WORKERS:-4}
MAX_TRAIN_FRAMES=${MAX_TRAIN_FRAMES:-0}

# Global improved defaults
ROI_LEVELS=${ROI_LEVELS:-256}
BG_LEVELS=${BG_LEVELS:-16}
ROI_TARGET_MODE=${ROI_TARGET_MODE:-maxpool}
QUANTIZER_MODE=${QUANTIZER_MODE:-adaptive}
QUANT_BITS=${QUANT_BITS:-8}

L_RECON=${L_RECON:-1.0}
L_RATE=${L_RATE:-0.02}
L_IMPORTANCE=${L_IMPORTANCE:-1.0}
L_IMP_SEPARATION=${L_IMP_SEPARATION:-0.2}
IMP_SEPARATION_MARGIN=${IMP_SEPARATION_MARGIN:-0.05}

LOSS_RECIPE=${LOSS_RECIPE:-balanced_v2}
RATE_LOSS_MODE=${RATE_LOSS_MODE:-normalized_bg}
IMPORTANCE_LOSS_MODE=${IMPORTANCE_LOSS_MODE:-weighted_bce}
IMPORTANCE_POS_WEIGHT_MODE=${IMPORTANCE_POS_WEIGHT_MODE:-auto}
IMPORTANCE_POS_WEIGHT=${IMPORTANCE_POS_WEIGHT:-1.0}
IMPORTANCE_POS_WEIGHT_MAX=${IMPORTANCE_POS_WEIGHT_MAX:-50.0}

DISTILL_LOGIT_LOSS=${DISTILL_LOGIT_LOSS:-auto}
DISTILL_TEMPERATURE=${DISTILL_TEMPERATURE:-1.0}
DISTILL_FEATURE_WEIGHT=${DISTILL_FEATURE_WEIGHT:-1.0}
DISTILL_LOGIT_WEIGHT=${DISTILL_LOGIT_WEIGHT:-1.0}

IMPORTANCE_HEAD_TYPE=${IMPORTANCE_HEAD_TYPE:-pp_lite}
IMPORTANCE_HIDDEN_CHANNELS=${IMPORTANCE_HIDDEN_CHANNELS:-64}

TEACHER_BACKEND=${TEACHER_BACKEND:-pointpillars_zhulf}
TEACHER_PROXY_CKPT=${TEACHER_PROXY_CKPT:-data/checkpoints/pointpillars_epoch_160.pth}

RUN_STAGE2_DARKNET=${RUN_STAGE2_DARKNET:-1}
RUN_STAGE2_RESNET=${RUN_STAGE2_RESNET:-1}

if [[ ! -f "${TEACHER_PROXY_CKPT}" ]]; then
  echo "Warning: teacher checkpoint not found at ${TEACHER_PROXY_CKPT}" >&2
fi

jid_s0=$(
  sbatch \
    --export=ALL,EPOCHS="${EPOCHS}",BATCH_SIZE="${BATCH_SIZE}",NUM_WORKERS="${NUM_WORKERS}",MAX_TRAIN_FRAMES="${MAX_TRAIN_FRAMES}",L_RECON=1.0,L_RATE=0.0,L_DISTILL=0.0,L_IMPORTANCE=0.0 \
    src/scripts/run_uniform_baseline.sh | awk '{print $4}'
)

jid_s1=$(
  sbatch \
    --export=ALL,EPOCHS="${EPOCHS}",BATCH_SIZE="${BATCH_SIZE}",NUM_WORKERS="${NUM_WORKERS}",MAX_TRAIN_FRAMES="${MAX_TRAIN_FRAMES}",ROI_LEVELS="${ROI_LEVELS}",BG_LEVELS="${BG_LEVELS}",ROI_TARGET_MODE="${ROI_TARGET_MODE}",QUANTIZER_MODE="${QUANTIZER_MODE}",QUANT_BITS="${QUANT_BITS}",LOSS_RECIPE="${LOSS_RECIPE}",RATE_LOSS_MODE="${RATE_LOSS_MODE}",IMPORTANCE_LOSS_MODE="${IMPORTANCE_LOSS_MODE}",IMPORTANCE_POS_WEIGHT_MODE="${IMPORTANCE_POS_WEIGHT_MODE}",IMPORTANCE_POS_WEIGHT="${IMPORTANCE_POS_WEIGHT}",IMPORTANCE_POS_WEIGHT_MAX="${IMPORTANCE_POS_WEIGHT_MAX}",L_RECON="${L_RECON}",L_RATE="${L_RATE}",L_DISTILL=0.0,L_IMPORTANCE="${L_IMPORTANCE}",L_IMP_SEPARATION="${L_IMP_SEPARATION}",IMP_SEPARATION_MARGIN="${IMP_SEPARATION_MARGIN}",DISTILL_LOGIT_LOSS="${DISTILL_LOGIT_LOSS}",DISTILL_TEMPERATURE="${DISTILL_TEMPERATURE}",DISTILL_FEATURE_WEIGHT="${DISTILL_FEATURE_WEIGHT}",DISTILL_LOGIT_WEIGHT="${DISTILL_LOGIT_WEIGHT}",IMPORTANCE_HEAD_TYPE="${IMPORTANCE_HEAD_TYPE}",IMPORTANCE_HIDDEN_CHANNELS="${IMPORTANCE_HIDDEN_CHANNELS}" \
    src/scripts/run_stage1.sh | awk '{print $4}'
)

jid_s2_darknet=""
if [[ "${RUN_STAGE2_DARKNET}" == "1" ]]; then
  jid_s2_darknet=$(
    sbatch \
      --export=ALL,BACKBONE=darknet,EPOCHS="${EPOCHS}",BATCH_SIZE="${BATCH_SIZE}",NUM_WORKERS="${NUM_WORKERS}",MAX_TRAIN_FRAMES="${MAX_TRAIN_FRAMES}",ROI_LEVELS="${ROI_LEVELS}",BG_LEVELS="${BG_LEVELS}",ROI_TARGET_MODE="${ROI_TARGET_MODE}",QUANTIZER_MODE="${QUANTIZER_MODE}",QUANT_BITS="${QUANT_BITS}",LOSS_RECIPE="${LOSS_RECIPE}",RATE_LOSS_MODE="${RATE_LOSS_MODE}",IMPORTANCE_LOSS_MODE="${IMPORTANCE_LOSS_MODE}",IMPORTANCE_POS_WEIGHT_MODE="${IMPORTANCE_POS_WEIGHT_MODE}",IMPORTANCE_POS_WEIGHT="${IMPORTANCE_POS_WEIGHT}",IMPORTANCE_POS_WEIGHT_MAX="${IMPORTANCE_POS_WEIGHT_MAX}",L_RECON="${L_RECON}",L_RATE="${L_RATE}",L_IMPORTANCE="${L_IMPORTANCE}",L_IMP_SEPARATION="${L_IMP_SEPARATION}",IMP_SEPARATION_MARGIN="${IMP_SEPARATION_MARGIN}",DISTILL_LOGIT_LOSS="${DISTILL_LOGIT_LOSS}",DISTILL_TEMPERATURE="${DISTILL_TEMPERATURE}",DISTILL_FEATURE_WEIGHT="${DISTILL_FEATURE_WEIGHT}",DISTILL_LOGIT_WEIGHT="${DISTILL_LOGIT_WEIGHT}",IMPORTANCE_HEAD_TYPE="${IMPORTANCE_HEAD_TYPE}",IMPORTANCE_HIDDEN_CHANNELS="${IMPORTANCE_HIDDEN_CHANNELS}",TEACHER_BACKEND="${TEACHER_BACKEND}",TEACHER_PROXY_CKPT="${TEACHER_PROXY_CKPT}" \
      src/scripts/run_stage2.sh | awk '{print $4}'
  )
fi

jid_s2_resnet=""
if [[ "${RUN_STAGE2_RESNET}" == "1" ]]; then
  jid_s2_resnet=$(
    sbatch \
      --export=ALL,BACKBONE=resnet,EPOCHS="${EPOCHS}",BATCH_SIZE="${BATCH_SIZE}",NUM_WORKERS="${NUM_WORKERS}",MAX_TRAIN_FRAMES="${MAX_TRAIN_FRAMES}",ROI_LEVELS="${ROI_LEVELS}",BG_LEVELS="${BG_LEVELS}",ROI_TARGET_MODE="${ROI_TARGET_MODE}",QUANTIZER_MODE="${QUANTIZER_MODE}",QUANT_BITS="${QUANT_BITS}",LOSS_RECIPE="${LOSS_RECIPE}",RATE_LOSS_MODE="${RATE_LOSS_MODE}",IMPORTANCE_LOSS_MODE="${IMPORTANCE_LOSS_MODE}",IMPORTANCE_POS_WEIGHT_MODE="${IMPORTANCE_POS_WEIGHT_MODE}",IMPORTANCE_POS_WEIGHT="${IMPORTANCE_POS_WEIGHT}",IMPORTANCE_POS_WEIGHT_MAX="${IMPORTANCE_POS_WEIGHT_MAX}",L_RECON="${L_RECON}",L_RATE="${L_RATE}",L_IMPORTANCE="${L_IMPORTANCE}",L_IMP_SEPARATION="${L_IMP_SEPARATION}",IMP_SEPARATION_MARGIN="${IMP_SEPARATION_MARGIN}",DISTILL_LOGIT_LOSS="${DISTILL_LOGIT_LOSS}",DISTILL_TEMPERATURE="${DISTILL_TEMPERATURE}",DISTILL_FEATURE_WEIGHT="${DISTILL_FEATURE_WEIGHT}",DISTILL_LOGIT_WEIGHT="${DISTILL_LOGIT_WEIGHT}",IMPORTANCE_HEAD_TYPE="${IMPORTANCE_HEAD_TYPE}",IMPORTANCE_HIDDEN_CHANNELS="${IMPORTANCE_HIDDEN_CHANNELS}",TEACHER_BACKEND="${TEACHER_BACKEND}",TEACHER_PROXY_CKPT="${TEACHER_PROXY_CKPT}" \
      src/scripts/run_stage2.sh | awk '{print $4}'
  )
fi

echo "Submitted improved 150-epoch jobs:"
echo "  Stage0 uniform sweep   : ${jid_s0} (array 0-5)"
echo "  Stage1 adaptive sweep  : ${jid_s1} (array 0-3)"
if [[ -n "${jid_s2_darknet}" ]]; then
  echo "  Stage2 distill darknet : ${jid_s2_darknet} (array 0-2)"
fi
if [[ -n "${jid_s2_resnet}" ]]; then
  echo "  Stage2 distill resnet  : ${jid_s2_resnet} (array 0-2)"
fi
echo ""
echo "Monitor with:"
echo "  squeue -j ${jid_s0},${jid_s1}${jid_s2_darknet:+,${jid_s2_darknet}}${jid_s2_resnet:+,${jid_s2_resnet}}"
